## Задача: сравнение предложений

Дан набор предложений, скопированных из Википедии. Каждое из них имеет "кошачью тему" в одном из трех смыслов:

кошки (животные)
UNIX-утилита cat для вывода содержимого файлов
версии операционной системы OS X, названные в честь семейства кошачьих

**Задача** — найти два предложения, которые ближе всего по смыслу к расположенному в самой первой строке. В качестве меры близости по смыслу мы будем использовать косинусное расстояние.

In [3]:
import numpy as np
import re
import pandas as pd
import scipy.spatial.distance
#f = open('sentences.txt')
#f.readlines()
with open('sentences.txt') as file:
    text = file.readlines()
#print (text)
l = []
for line in text:
    x= line.lower()
    s =re.split('[^a-z]', x)
    #print(s)
    l.append(s)
    
v=[]
for i in l:
    if type(i) is list:
        v.extend(i)
    else:
        v.append(i)
print (l)

[['in', 'comparison', 'to', 'dogs', '', 'cats', 'have', 'not', 'undergone', 'major', 'changes', 'during', 'the', 'domestication', 'process', '', ''], ['as', 'cat', 'simply', 'catenates', 'streams', 'of', 'bytes', '', 'it', 'can', 'be', 'also', 'used', 'to', 'concatenate', 'binary', 'files', '', 'where', 'it', 'will', 'just', 'concatenate', 'sequence', 'of', 'bytes', '', ''], ['a', 'common', 'interactive', 'use', 'of', 'cat', 'for', 'a', 'single', 'file', 'is', 'to', 'output', 'the', 'content', 'of', 'a', 'file', 'to', 'standard', 'output', '', ''], ['cats', 'can', 'hear', 'sounds', 'too', 'faint', 'or', 'too', 'high', 'in', 'frequency', 'for', 'human', 'ears', '', 'such', 'as', 'those', 'made', 'by', 'mice', 'and', 'other', 'small', 'animals', '', ''], ['in', 'one', '', 'people', 'deliberately', 'tamed', 'cats', 'in', 'a', 'process', 'of', 'artificial', 'selection', '', 'as', 'they', 'were', 'useful', 'predators', 'of', 'vermin', '', ''], ['the', 'domesticated', 'cat', 'and', 'its', 'c

In [8]:
bp = [i for i in v if i]
mn = set(bp)
d = len(mn)
n = len(text)
print (n,d)
print (mn)

22 254
{'run', 'mice', 'released', 'chromosomes', 'where', 'when', 'which', 'adjacent', 'terms', 'roughly', 'update', 'too', 'community', 'online', 'comparison', 'release', 'linux', 'small', 'possess', 'may', 'concatenate', 'some', 'contains', 'made', 'streams', 'typically', 'disk', 'features', 'create', 'ears', 'switch', 'allows', 'often', 'off', 'arguments', 'most', 'installs', 'stdin', 'single', 't', 'animals', 'external', 'lb', 'permanently', 'any', 'fifth', 'major', 'such', 'used', 'recent', 'legibility', 'domesticated', 'kg', 'basic', 'have', 'versions', 'mavericks', 'not', 'learned', 'domestic', 'world', 'high', 'for', 'with', 'x', 'installed', 'needing', 'interactive', 'during', 'leopard', 'mid', 'members', 'releasing', 'starting', 'useful', 'started', 'allow', 'can', 'separate', 'cat', 'size', 'predators', 'predecessor', 'now', 'developed', 'were', 'diploid', 'successor', 'one', 'they', 'other', 'received', 'hear', 'genes', 'time', 'it', 'wild', 'was', 'purchase', 'osx', 'firm

In [71]:
posl = []
for i in mn:
    for lis in l:
        if i in lis:
            k = 0
            for elem in lis:
                if elem == i:
                    k += 1
                else:
                    continue
            posl.append(k)
            #print(k)
        else:
            posl.append(0)
npmas = np.asarray(posl)
npmasrs = npmas.reshape(d,n)
tm = np.transpose(npmasrs)
print (tm.shape)
print (tm)
print (tm[0])

(22, 254)
[[0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 1]
 [1 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]


In [127]:
import scipy.spatial.distance
lkosdist = []
for stroka in tm:
    kosdist = scipy.spatial.distance.cosine(tm[0],stroka)
    lkosdist.append(kosdist)
#print (lkosdist)
sort = sorted(lkosdist)
otvet1 = lkosdist.index(sort[1])
otvet2 = lkosdist.index(sort[2])
print( otvet1, otvet2)

6 4
